### ISSUE TITLE
kerberos.authGSSClientClean is deprecated

### ISSUE THREAD

**Issue by mcepl** [psss/did#100]
When getting issues out of Jira I get this `Runtime Error`:

```
/usr/lib/python2.7/site-packages/urllib2_kerberos.py:147: RuntimeError: kerberos.authGSSClientClean is deprecated.
  self.clean_context()
```

**Comment by mfrodl** [comment]
This is a [`pykerberos` issue](https://github.com/02strich/pykerberos/issues/19) which has been [fixed](https://github.com/02strich/pykerberos/commit/c74fce17142b355cb333b05ddb6382ec4fd1c21e) in version 1.1.12. Please update your `pykerberos` to the latest version (`pip install --upgrade pykerberos`) and try running JIRA plugin again. The warning should not show up anymore.
