### ISSUE TITLE
Implement GitHub plugin comment stats

### ISSUE THREAD

**Issue by rgbriggs** [psss/did#128]
It would be great to have comment statistics available for the github plugin as is done for bugzilla, both number of issues/pullRequests commented, but comments per issue/PR as well.

**Comment by sandrobonazzola** [comment]
Or at leas as for Bugzilla:
```
* Bugs commented: 2
    * BZ#<bz number> - <bz title>
    * BZ#<bz number> - <bz title>
```

rendered for GitHub plugin as:
```
* Issues commented: 2
  *  <org/repo/issue#> - <issue title>
  *  <org2/repo2/issue#> - <issue title>
```
