### ISSUE TITLE
Don't go over unrecognised types from config files

### ISSUE THREAD

**Issue by lukaszachy** [psss/did#148]
Add invalid entry to config file, e.g. ``[zzz] type=abc`` and did will gracefully go over this entry. 
Real world problem is plugin can disappear from pythonpath, typo can be made and user receives no warning at all.

In ideal world this will be fatal error (among lines of unrecognised type)

**Comment by psss** [comment]
Makes sense. We should ensure that such errors do not go by unnoticed.
