### ISSUE TITLE
Broken pip package?

### ISSUE THREAD

**Issue by gundalow** [psss/did#161]
```
sudo pip install did
Collecting did
  Could not find a version that satisfies the requirement did (from versions: )
No matching distribution found for did
```
Same for pip3

Python 2.7.12
Python 3.5.2

Is the package broken? https://pypi.org/project/did/ `<closed file ‘README.rst’, mode ‘r’ at 0x7f651240e420>`

**Comment by psss** [comment]
This should now be fixed for Python 2. Could you please check?
We need to move to Python 3 completely in the near future.

**Comment by gundalow** [comment]
Fixed, thanks

**Comment by psss** [comment]
Thanks for verifying.
