### ISSUE TITLE
What did you do last week, month, year?

### ISSUE THREAD

**Issue by psss** [psss/did#17]
The only thing I don't like about status-report is its name.
It's just too long and complicated to write on command line.
What about choosing something more comfortable and beautiful?

Commit d4cdbd2 shows how this could look like...
Usage like `did last week` seems quite natural ;-)

**Comment by psss** [comment]
Documentation looks nicer as well :-)
http://status-report.readthedocs.org/en/did/

**Comment by psss** [comment]
Or, `dyd`, what Dyd You Do last week :-)

**Comment by kejbaly2** [comment]
I like 'did' more than dyd

**Comment by psss** [comment]
Thanks for the feedback, Chris.
I chose `did` then and did it in d4cdbd2 :-)
