### ISSUE TITLE
Bugzilla verified bug not recognized when different QA Contact

### ISSUE THREAD

**Issue by jakub-vavra** [psss/did#189]
It seems that did does not recognize that I have verified a bug when I am not the "QA Contact", which is the usual situation as we have a team mailing list in there instead of personal e-mails.

**Comment by psss** [comment]
If I remember correctly, the original way how to identify verified bugs was the `changedby` email which you propose in #190. However we changed the behaviour in order to better cover bugs where the actual switch of the bug state is performed by an automation tool, which has a different email address. So using the QA Contact field here seems to be more reliable. Is there a process which prevents you to update the QA Contact with your email?

**Comment by jakub-vavra** [comment]
Well, we do keep there the mailing list so the updates to the bug are visible to team members and it is easy to query for the team bugs using the QE Contact.

Can we change the query to use OR so both ways can be used or possibly merge results of two separate queries?

**Comment by psss** [comment]
I see, thanks for clarification. Extending the query with `or` to cover both use cases seems like a good solution and should not break anything, as far as I can see.

**Comment by jakub-vavra** [comment]
I did a quick check and was unable to figure out how to add the OR to the query.
I have added second query with changedby and merge logic so bugs where the qa contact and chagedby are the same are not listed twice.

**Comment by jakub-vavra** [comment]
I have added test for the change in the second commit so the overall coverage is slightly better now.
Let me know if there is something I should improve before this can be merged.

**Comment by psss** [comment]
Thanks for the enhanced fix and extending the test suite. Advanced Bugzilla queries can be nicely explored directly from the [web interface](https://bugzilla.redhat.com/query.cgi?format=advanced). See `Custom Search` at the bottom, set up your query and then check generated URL. I've modified your fix to use just a single query. Bugzilla queries are slow so it makes sense to optimize. Tests are passing. Going to merge.
