### ISSUE TITLE
Jira plugin doesn't show any message when there are warnings in the output

### ISSUE THREAD

**Issue by emanchado** [psss/did#201]
Jira searches can yield warnings. I don't know how common they are, but if you eg. make a mistake in your username, Jira will never find anything relevant, and will return a warning.

Intuitively, as the search query is basically fixed, I would expect that these warnings would be quite important and would mean that the result is not what the user wanted. Hence, it would be nice if `did` showed a message, or maybe even die with an error, if the Jira server returned any `warningMessages`.

Here is an example of such a response, although I guess it's trivial to reproduce by giving a wrong username:

```{u'issues': [],
 u'maxResults': 1000,
 u'startAt': 0,
 u'total': 0,
 u'warningMessages': [u"The value 'esteban@redhat.com' does not exist for the field 'creator'."]}```

**Comment by psss** [comment]
Thanks for reporting the issue. It should be fixed by #248.
