### ISSUE TITLE
Strange characters when output is redirected

### ISSUE THREAD

**Issue by lzap** [psss/did#211]
Hey, when I redirect the output to mailx it comes with some strange characters. This does not look like terminal control characters, it's weird:

```
b'Status report for the week 47 (2019-11-18 to 2019-11-24).'
b'\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n xxx@redhat.com\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~'

b'* Bugs posted: 3'
b'    * BZ#1713194 - [RFE] New check - warning when there are many fact names'
b'    * BZ#1715999 - Use Infoblox API for DNS conflict check and not system resolver'
b'    * BZ#1770999 - SELinux denials when connecting to cockpit using REX'
```

Any clue what are these? Be for binary mabye? UTF-8 encoding issue?

**Comment by psss** [comment]
Seems with python3 it's no more necessary to explicitly handle scenario without a tty attached. Let's remove the custom `eprint()` function.
