### ISSUE TITLE
Quarterly reports for calendar quarter

### ISSUE THREAD

**Issue by brakogh** [psss/did#223]
When using quarter for time range (did last quarter), did is currently using Financial Year (FY) quarters (March -> May), that doesn't match calendar year (CY) quarters (April -> Jun).
Please change did to use CY quarters instead of FY ones.

**Comment by psss** [comment]
We should make it configurable where the first quarter starts.

**Comment by brakogh** [comment]
Any progress here? We already really need this feature for reporting.

**Comment by psss** [comment]
Unfortunately nobody found time to make this configurable. I've created a simple pull request #224 which changes the default quarter alignment from fiscal year to calendar year. We can possibly leave the config feature for the future...

**Comment by hegerj** [comment]
@psss Is there a reason to make configurable at all? It seems to me most people would want to use CY quarters.

**Comment by psss** [comment]
> @psss Is there a reason to make configurable at all? It seems to me most people would want to use CY quarters.

If possible I always try to prevent any backward-incompatible changes. And if it's not possible I think it's good to at least provide a way how to enable the previous behaviour. In this case it really seems the default should be changed to the first month as majority of current users switched to the calendar year quarters. Change merged into master.
