### ISSUE TITLE
Add support for loading Jira/Confluence password from a file

### ISSUE THREAD

**Issue by jharuda** [psss/did#228]
When I use basic authentication for Jira or Confluence, the `auth_password` option must be set in `~/.did/config`.

However, saving passwords directly to the configuration file is not so great.
When we currently use `auth_password`, we mix configuration parts and passwords, and we also must to fill a password in each Jira/Confluence section.
I think it would be good enhancement if we can add support for loading passwords from separate valut/password files.

We need to store the path to a vault file somewhere.
So we need to add a new option. Something like: `auth_valut`, `auth_password_valut`, `auth_valut_file` or `auth_password_file`.

examples of such a configuration
auth_username = user
auth_valut_file = ~/.did/.valut_jira

auth_username = user
auth_valut_file = ~/.did/.valut_confluence

**Comment by psss** [comment]
Thanks for the idea, sounds good. As far as naming is concerned, `auth_password_file` seems to me to be the most straightforward and the most clear candidate.

**Comment by jharuda** [comment]
It was resolved in the past by #230.
