### ISSUE TITLE
JIRA SSO login

### ISSUE THREAD

**Issue by akostadinov** [psss/did#231]
Hi, trying to use https://issues.redhat.com but I can't login to it in any way. Any idea how use it with `did`?

**Comment by psss** [comment]
Sorry for the late response. It seems we need to implement a different authentication for the new server. Unfortunately, nobody has found time to look into this. This includes me, currently just too many things on the plate. But patches are mostly welcome!

**Comment by sandrobonazzola** [comment]
I'm able to get stats from https://issues.redhat.com/ by using a token as described in https://did.readthedocs.io/en/latest/plugins.html#module-did.plugins.jira

**Comment by psss** [comment]
Yeap, works for me as well. @sandrobonazzola, thanks for verification. @akostadinov, feel free to reopen if you still experience the issue.
