### ISSUE TITLE
Github Private Repo Access

### ISSUE THREAD

**Issue by jeffscottward** [psss/did#232]
Hello,

It's not clear to me how I would generate a report against my private repos at work.
I'm part of an org on github (my company), and use a main personal email to login to my github (Gmail) - but also have a work email.

I generated a personal token but it doesn't seem to be able to reach into private repos.

Am I missing something?

**Comment by psss** [comment]
The github reports should not depend on your email address. Do you have a `login = jeffscottward` defined in your configuration? That, together with a valid token, should be all that is needed. See the [github](https://did.readthedocs.io/en/latest/plugins/#module-did.plugins.github) plugin documentation for a full config example. At least that's what I would expect from the API, I haven't tested with any private repo so far.
