### ISSUE TITLE
Can't read Jira issues

### ISSUE THREAD

**Issue by daobrien** [psss/did#245]
I don't know if this is an issue with my config or something else, but I can't get `did` to read from our Jira instance https://training-feedback.redhat.com/secure/Dashboard.jspa
I've tried several variations of the configs in the docs but so far can't get it to work.
Note that this instance does not use SSO.
~~~
Traceback (most recent call last):
  File "/usr/bin/did", line 42, in <module>
    did.cli.main()
  File "/usr/lib/python3.9/site-packages/did/cli.py", line 222, in main
    user_stats.check()
  File "/usr/lib/python3.9/site-packages/did/stats.py", line 157, in check
    stat.check()
  File "/usr/lib/python3.9/site-packages/did/stats.py", line 157, in check
    stat.check()
  File "/usr/lib/python3.9/site-packages/did/stats.py", line 77, in check
    self.fetch()
  File "/usr/lib/python3.9/site-packages/did/plugins/jira.py", line 162, in fetch
    self.stats = Issue.search(query, stats=self)
  File "/usr/lib/python3.9/site-packages/did/plugins/jira.py", line 123, in search
    batch, listed(data["issues"], "issue")))
KeyError: 'issues'
~~~

**Comment by psss** [comment]
What currently works for the public jira instance is this:

```
[jira]
type = jira
url = https://issues.redhat.com/
auth_type = basic
auth_url = https://issues.redhat.com/rest/auth/latest/session
auth_username = <login>
auth_password = <password>
```

I'm not sure if the other jira instance is different in some way. You can try running `did` in debug mode:

    DEBUG=5 did

It should give you some more details about the server response.

**Comment by daobrien** [comment]
Thanks for the quick response. I used the config you posted and just swapped out the URLs. I ran `DEBUG=5 did` and received this output:
~~~
<...output omitted...>
 INFO  Searching for CheckItem completed in trello by David O'Brien <daobrien@redhat.com>
 DATA  []
 INFO  Searching for issues created in None by David O'Brien <daobrien@redhat.com>
 DEBUG  Search query: creator = 'daobrien@redhat.com' AND created >= 2021-09-20 AND created <= 2021-09-27
 DEBUG  Connecting to https://training-feedback.redhat.com/rest/auth/latest/session
 DEBUG  Batch 0 result: 0 issues fetched
 DATA  {'issues': [], 'maxResults': 1000, 'startAt': 0, 'total': 0}
 INFO  Searching for issues updated in None by David O'Brien <daobrien@redhat.com>
 DEBUG  Search query: issueFunction in commented('by daobrien after 2021-09-20 before 2021-09-27')
Traceback (most recent call last):
  File "/usr/bin/did", line 42, in <module>
    did.cli.main()
  File "/usr/lib/python3.9/site-packages/did/cli.py", line 222, in main
    user_stats.check()
  File "/usr/lib/python3.9/site-packages/did/stats.py", line 157, in check
    stat.check()
  File "/usr/lib/python3.9/site-packages/did/stats.py", line 157, in check
    stat.check()
  File "/usr/lib/python3.9/site-packages/did/stats.py", line 77, in check
    self.fetch()
  File "/usr/lib/python3.9/site-packages/did/plugins/jira.py", line 179, in fetch
    self.stats = Issue.search(query, stats=self)
  File "/usr/lib/python3.9/site-packages/did/plugins/jira.py", line 123, in search
    batch, listed(data["issues"], "issue")))
KeyError: 'issues'
~~~
I'm curious about this:
`Searching for issues updated in None `
Do I need to specify projects (there are lots). I tried `project = *` but received the same error.

I also used the same config that you posted above to try and connect to the public instance, but got the same error. I can access both sites in a browser no problem.

**Comment by psss** [comment]
>  Do I need to specify projects (there are lots). I tried `project = *` but received the same error.

The `project` key used to be mandatory, but should not be any more. You can, however, try to provide a single project if there would be any difference.

> Thanks for the quick response. I used the config you posted and just swapped out the URLs. I ran `DEBUG=5 did` and received this output:

Hm, apparently the received `data` are not in the expected format. Could you try to remove or comment [lines 122 and 123](https://github.com/psss/did/blob/master/did/plugins/jira.py#L122) so that we actually see what `data` contains (line 124)?

**Comment by daobrien** [comment]
I currently don't have any projects specified in the config.
Now I'm getting this:
~~~
 DEBUG  Connecting to https://training-feedback.redhat.com/rest/auth/latest/session
 DATA  {'issues': [], 'maxResults': 1000, 'startAt': 0, 'total': 0}
 INFO  Searching for issues updated in None by David O'Brien <daobrien@redhat.com>
 DEBUG  Search query: issueFunction in commented('by daobrien after 2021-09-20 before 2021-09-27')
 DATA  {'errorMessages': ["Field 'issueFunction' does not exist or you do not have "
                   'permission to view it.'],
 'errors': {}}
Traceback (most recent call last):
  File "/usr/bin/did", line 42, in <module>
    did.cli.main()
  File "/usr/lib/python3.9/site-packages/did/cli.py", line 222, in main
    user_stats.check()
  File "/usr/lib/python3.9/site-packages/did/stats.py", line 157, in check
    stat.check()
  File "/usr/lib/python3.9/site-packages/did/stats.py", line 157, in check
    stat.check()
  File "/usr/lib/python3.9/site-packages/did/stats.py", line 77, in check
    self.fetch()
  File "/usr/lib/python3.9/site-packages/did/plugins/jira.py", line 179, in fetch
    self.stats = Issue.search(query, stats=self)
  File "/usr/lib/python3.9/site-packages/did/plugins/jira.py", line 125, in search
    issues.extend(data["issues"])
KeyError: 'issues'
~~~

**Comment by daobrien** [comment]
Note that if I try to connect to the public instance I get a different error:
(Using `auth_username = rhn-engineering-daobrien`)

~~~
 INFO  Searching for issues updated in None by David O'Brien <daobrien@redhat.com>
 DEBUG  Search query: issueFunction in commented('by daobrien after 2021-09-20 before 2021-09-27')
 DATA  {'errorMessages': ['Cannot find user with username: daobrien. ',
                   'The argument should be in the form ("by jbloggs"), or any '
                   'of ("by jbloggs on Date after Date before Date inRole Role '
                   'inGroup Group roleLevel Role groupLevel Group"). Date can '
                   'be either a date or an expression like -5d or -8w, or a '
                   'function like startOfMonth().'],
 'errors': {}}
~~~
...followed by the same stacktrace as above.

**Comment by daobrien** [comment]
> Note that if I try to connect to the public instance I get a different error:
> (Using `auth_username = rhn-engineering-daobrien`)
> 
> ```
>  INFO  Searching for issues updated in None by David O'Brien <daobrien@redhat.com>
>  DEBUG  Search query: issueFunction in commented('by daobrien after 2021-09-20 before 2021-09-27')
>  DATA  {'errorMessages': ['Cannot find user with username: daobrien. ',
>                    'The argument should be in the form ("by jbloggs"), or any '
>                    'of ("by jbloggs on Date after Date before Date inRole Role '
>                    'inGroup Group roleLevel Role groupLevel Group"). Date can '
>                    'be either a date or an expression like -5d or -8w, or a '
>                    'function like startOfMonth().'],
>  'errors': {}}
> ```
> 
> ...followed by the same stacktrace as above.

I fixed this for the public instance by using `login = rhn-engineering-daobrien`

**Comment by psss** [comment]
Good to hear you were able to fix this for the public instance. Have you checked the profile details of the training instance for the proper user name there? Anyway, we should give a better error upon such failures. This should be addressed by #248.

**Comment by daobrien** [comment]
~~~
INFO  Searching for issues updated in None by David O'Brien <daobrien@redhat.com>
 DEBUG  Search query: issueFunction in commented('by rht-daobrien after 2021-09-20 before 2021-09-27')
 DATA  {'errorMessages': ["Field 'issueFunction' does not exist or you do not have "
                   'permission to view it.'],
~~~
The name, the email, and the username are all correct in this output.

The config file uses the following:
~~~
login = rht-daobrien
auth_type = basic
auth_url = https://training-feedback.redhat.com/login.jsp?nosso
auth_username = rht-daobrien
~~~
I'm not 100% sure about the `auth_url` but that doesn't seem to be the issue afaict.

**Comment by psss** [comment]
Seems the instance does not support `scriptrunner`, could you try with the following?

    use_scriptrunner = false

But then you have to provide `project` if I remember correctly. If needed, @sochotnicky might provide some more details as he implemented the `issueFunction` speed-up in #198.

**Comment by psss** [comment]
Sorry, I just merged the fix for a better error message which closed the issue. If I remember correctly, without the `scriptrunner` it is not possible to search across all projects, @sochotnicky can possibly provide more details. So, as a workaround I suggest to create multiple jira sections, each with a single project. That's what I used as well before the `scriptrunner` was introduced.

**Comment by daobrien** [comment]
I was hoping you weren't going to say that. We have *stacks* of projects to deal with. I could probably exclude some of the older ones that don't get much of a look, but it's still a long list. I know I'm getting off topic now, but is there a way to have multiple config files so that I can maybe manage Jira projects separately? I read GitHub and Trello as well and it'd be nice to separate things a bit.

**Comment by sochotnicky** [comment]
WRT scriptrunner etc - I have a vague memory that new JIRAs were planning/supposed to support the support "commented by <X>" type queries but I have not looked into this in ages so my info can be out of date. 

But basically - no scriptrunner means we can do a query such as `issueFunction in commented ('by {0} after {1} before {2}')` and without it - the only way is the fallback and doing one config section per project. And the behaviour is slightly different of course (i.e. scriptrunner actually only listed comments added not any random changes done in JIRAs such as adding a label etc)

**Comment by psss** [comment]
Regarding multiple configs: Yes, it's definitely possible. You can create for example `~/.did/jira` file with:

```
[one]
type = jira
project = one
url = https://issues.redhat.com/

[two]
type = jira
project = two
url = https://issues.redhat.com/

[three]
type = jira
project = three
url = https://issues.redhat.com/
```

And run the query using `did --config jira`.
