### ISSUE TITLE
did fails to interpret `\n` in the config file

### ISSUE THREAD

**Issue by daobrien** [psss/did#268]
Perhaps I'm "misusing" `did` but before I run my daily reports I update the `Next` section of the footer. I would like to update it so that `did` can produce something like this:

- Morning plans
- Afternoon plans
- Evening plans

I inject the different strings into the config file, separated by `\n`, but `did` doesn't interpret these. How can I achieve this?

thanks

**Comment by daobrien** [comment]
Is there any way to "bump" these or otherwise increase their priority? I guess we need more ppl to vote for the issue, but I wish for this almost every day. Thanks

**Comment by psss** [comment]
Sorry for the late reply, `did` is open for pull requests ;-) Anyway, could you please provide the full config for the above-mentioned use case? It would help to better understand your expectations.

**Comment by daobrien** [comment]
This is one day's example of `[footer]`:
~~~
[footer]
type = footer
next = *T:* Video editing
status = *No Blockers*
~~~

For the next day, I'd sometimes have a list of tasks, which I'd like present as a bulleted list rather than as a series:
~~~
[footer]
type = footer
next = *T:* Video editing \n * PR reviews \n * Video demonstration
status = *No Blockers*
~~~

Hopefully with an output something like this:
~~~
* *T:* 
* Video editing
* PR reviews
* Video demonstration
~~~

I've fiddled about with variations of `\n` etc., but can't make it work. Not being a coder I quickly ran out of ideas :(

**Comment by psss** [comment]
I see, thanks for explanation. Ok so what about #312? We would replace each escaped new line with a real one. For this config:

```
[footer]
type = footer
next = Main topic\n  * Item one\n  * Item two 
```

You would get this:

```
* Main topic
  * Item one
  * Item two
```

Does it cover your use case well?

**Comment by daobrien** [comment]
Thanks for looking into this. I thought it was doing the job and then realised what's actually happening. This is what I do:

1. Before I run `did`, I use `sed` to update the "Today" section of the config file, which to date has just been a single line.
2. Run `did`.
3. For the next iteration, run `sed` again to replace everything after "next" with the required string.

Unfortunately, what's happening now is that the newlines are being rendered and written into the config. This means that instead of operating on a single line, `sed` needs to work over multiple lines.

I might be asking too much of `did`, but if the config maintained a single-line statement of work and `did` itself interpreted newlines then I think we'd be good.

E.g., my `sed` expression produces this in the config file:

~~~
[footer]
type = footer
next = *T:*
 * Project planning proposal.
 * Update spellr.
 * Vale devel.
 * Various meetings.
status = *No Blockers*
~~~

And this renders as follows:

~~~
* *T:*
* Project planning proposal.
* Update spellr.
* Vale devel.
* Various meetings.

* *No Blockers*
~~~

That's fine, but next time I have to swap out 4 lines. The next time might be 2 lines, then 3 lines. Again, I might not be using `did` as you intended, or asking too much. Thanks again for looking into this.
Regards,
David

**Comment by psss** [comment]
Sorry, I got a bit lost. Could you please explain what is the intention of the two `sed` commands?

> Before I run `did`, I use `sed` to update the "Today" section of the config file, which to date has just been a single line.

In my example above, it still is a single line.

> Unfortunately, what's happening now is that the newlines are being rendered and written into the config.

New lines rendered in the config? They should be rendered just in the `did` output.

**Comment by daobrien** [comment]
> Sorry, I got a bit lost. Could you please explain what is the intention of the two `sed` commands?
> 
> > Before I run `did`, I use `sed` to update the "Today" section of the config file, which to date has just been a single line.
> 
> In my example above, it still is a single line.

It might be the way you and I are updating the config that's causing confusion. I'll provide a complete example.

UPDATE: This turned out to be the case. I need to escape the newlines in my `sed` expression so that they are passed to the `.did/config` file as a single line. Consider this PR approved :+1: 

Long version, if you're interested:

> 
> > Unfortunately, what's happening now is that the newlines are being rendered and written into the config.
> 
> New lines rendered in the config? They should be rendered just in the `did` output.

Initial `did` config:
~~~
[footer]
type = footer
next = *T:*\n * Video editing \n * PR reviews \n * Video demonstration
status = *No Blockers*
~~~
Resulting output:
~~~
* *T:*
 * Video editing 
 * PR reviews 
 * Video demonstration

* *No Blockers*
~~~
This is fine.
To update "next" for the next report, I use `sed` to do something like this:

`sed -i -e 's/next =.*/next = \*T:\*\n * Project planning proposal.\n * Update spellr.\n * Vale devel.\n * Various meetings./' ~/.did/config`

This produces the following in `~/.did/config`:

~~~
[footer]
type = footer
next = *T:*
 * Project planning proposal.
 * Update spellr.
 * Vale devel.
 * Various meetings.
status = *No Blockers*
~~~
With the following output from `did`:

~~~
* *T:*
* Project planning proposal.
* Update spellr.
* Vale devel.
* Various meetings.

* *No Blockers*
~~~

Updated `sed` expression to produce required output:

`sed -i -e 's/next =.*/next = \*T:\*\\n * Project planning proposal.\\n * Update spellr.\\n * Vale devel.\\n * Various meetings./' ~/.did/config`

**Comment by psss** [comment]
Ok, now I see, thanks for the detailed explanation. So the pull request is ok, good! I'll add some docs and merge it.

I have to admit I'm still surprised by using `sed` to regularly update `did` config file. Does it mean that you modify the configuration before generating each report? The main use case for `header` and `footer` was to provide a free-form space where one would just write manually those items which cannot be gathered from the tracking systems before sending it.

**Comment by daobrien** [comment]
I have to admit I'm a bit of a tinkerer, and often the "Today" update is simple. I just find it quicker and easier (especially using command history) to reuse a `sed` command. Thank you for doing this :+1:
