### ISSUE TITLE
Invalid plugin type 'google' in section 'google'.

### ISSUE THREAD

**Issue by fhrdina1** [psss/did#269]
Hi, after crash of my fc35, I installed fc36, since then, the google plugin stopped working. Maybe it is some issue on my side, not sure.

did.noarch                                             0.191.20220608202157703892.master.1.ge1a809d.fc36@copr:copr.fedorainfracloud.org:psss:did

config:
```
[google]
type = google
client_id = xxxxx
client_secret = xxxxx
apps = calendar,tasks
storage = /home/fhrdina/.did/creds.json
```

`did this week --debug`

```
Traceback (most recent call last):
  File "/usr/bin/did", line 42, in <module>
    did.cli.main()
  File "/usr/lib/python3.10/site-packages/did/cli.py", line 201, in main
    options, header = Options(arguments).parse()
  File "/usr/lib/python3.10/site-packages/did/cli.py", line 72, in __init__
    self.sample_stats = UserStats()
  File "/usr/lib/python3.10/site-packages/did/stats.py", line 187, in __init__
    self.stats = self.configured_plugins(config)
  File "/usr/lib/python3.10/site-packages/did/stats.py", line 220, in configured_plugins
    raise did.base.ConfigError(
did.base.ConfigError: Invalid plugin type 'google' in section 'google'.
```

**Comment by r0x0d** [comment]
I had the same problem today while installing `did` through dnf. 

What worked for me was removing it and installing it via pip. 

```bash
pip install did[google]
```

**Comment by fhrdina1** [comment]
> I had the same problem today while installing `did` through dnf.
> 
> What worked for me was removing it and installing it via pip.
> 
> ```shell
> pip install did[google]
> ```

Hi, thanks. 
This helped, but unfortunately, the others internal redhat plugins stopped working.

**Comment by psss** [comment]
For the `google` plugin there is an [additional dependency](https://did.readthedocs.io/en/latest/plugins.html#module-did.plugins.google) to be installed:

    sudo dnf install python3-google-api-client

Does this fix your problem when installing `did` using `dnf`?

**Comment by fhrdina1** [comment]
> For the `google` plugin there is an [additional dependency](https://did.readthedocs.io/en/latest/plugins.html#module-did.plugins.google) to be installed:
> 
> ```
> sudo dnf install python3-google-api-client python3-oauth2client
> ```
> 
> Does this fix your problem when installing `did` using `dnf`?

Combination of this and regenerating new credentials fixed it. Thank you for your help.

**Comment by psss** [comment]
Thanks for verifying. Updating docs in #270 to list both required packages.
