### ISSUE TITLE
Add support for tracking Git commits

### ISSUE THREAD

**Issue by daobrien** [psss/did#274]
I don't see a way to do this.

A lot of my daily work entails multiple commits to one or more branches, but `did` doesn't track any of this. afaict it only tracks issues and PRs.

thanks

**Comment by sandrobonazzola** [comment]
You can use the git plugin (see https://did.readthedocs.io/en/latest/plugins.html#module-did.plugins.git ) but you need a local clone of the git repository.

**Comment by daobrien** [comment]
Somehow I missed this but have it working now. Thanks.
