### ISSUE TITLE
`did last friday` - only friday supported?

### ISSUE THREAD

**Issue by achingbrain** [psss/did#305]
The `last friday` command example in the README is neat but unless I'm missing something only `friday` seems to be supported as a argument?

```console
% did last friday
Status report for the last friday (2023-05-12 to 2023-05-12).
... report here
```

```console
% did last thursday
 ERROR  Invalid argument: 'thursday'
```

```console
% did last wednesday
 ERROR  Invalid argument: 'wednesday'
```

```console
% did last tuesday  
 ERROR  Invalid argument: 'tuesday'
```

...etc

It'd be really nice any day could be used.

**Comment by psss** [comment]
Nice idea, sounds good! And should be fairly easy to implement:

https://github.com/psss/did/blob/9ceed73b7f7dcb03b30f267eca70a820b6257dcf/did/base.py#L332-L338

Pull request is welcome :)
