### ISSUE TITLE
Trello support

### ISSUE THREAD

**Issue by whitel** [psss/did#39]
would you look in to including some functionality like this? https://github.com/ghelleks/pbureport

**Comment by purpleidea** [comment]
Nobody counts doing things in Trello as real work, so I would NACK this idea.


...
Sorry, I'm just poking fun at the Trello folks out there... Carry on :)

**Comment by kejbaly2** [comment]
Haha

**Comment by kejbaly2** [comment]
see: https://github.com/maybelinot/did/tree/feat.trello

**Comment by purpleidea** [comment]
@kejbaly2 cool... hey @goern check it out.

**Comment by goern** [comment]
oh yeah... https://github.com/goern/yo-reporting

**Comment by psss** [comment]
I have reviewed #55, did a couple of adjustments to it in 285f07e and merged it to master.
