### ISSUE TITLE
Support for basic authentication in Jira plugin

### ISSUE THREAD

**Issue by TomasHofman** [psss/did#40]
While sending PR #35 which allowed connecting to issues.jboss.org, I didn't realize that jboss.org is not connected to Red Hat LDAP :). So while the jira plugin started to work for jboss.org, I wasn't actually authenticated and that prevents me from monitoring internal Red Hat projects.

It seems the only way to authenticate to jboss.org is via basic authentication (?)

I suggest defining following new properties for jira plugin:
- auth_type - 'gss' (default) or 'basic'
- auth_url - instead of sso_url to make it more general
- auth_username, auth_password - for defining credentials, only possible for 'basic' auth. type

I'm willing to work on this.

**Comment by psss** [comment]
Sounds good to me.

**Comment by mcepl** [comment]
What's wrong with GSS (aka SPNEGO)? We have support for it in https://github.com/psss/did/blob/master/did/plugins/jira.py#L194

**Comment by kejbaly2** [comment]
i also have this working in my requests kerberos branch, I believe... but
I'm not 100% sure I understand the problem.

**Comment by mcepl** [comment]
> i also have this working in my requests kerberos branch, I believe

Yes, you had, but I have rewritten it using plain urllib2 (resp. using my 193 lines urllib2_kerberos module). Don’t let me start what I think about the request module (and all its dependencies).

**Comment by TomasHofman** [comment]
@mcepl Do you use GSS authentication for issues.jboss.org? How do you login?

**Comment by mcepl** [comment]
Sorry, I don't use Jira at all (being RHEL QA), but somebody tested [appropriate bug](https://bugzilla.redhat.com/show_bug.cgi?id=1162249) and they seemed to be happy.

**Comment by TomasHofman** [comment]
The problem is not with Jira generally - I believe it's working, the problem is with Jira at issues.jboss.org - which doesn't support kerberos, or am I wrong?

**Comment by mcepl** [comment]
Probably. As I said, I am a RHEL guy, who was just annoyed with 500+k of useless dependencies.

**Comment by TomasHofman** [comment]
I'm not opposed to using urllib2, the problem with authentication would be the same with any other library.

Anyway, I have the solution done and working so I will push later today or tomorrow and you will see if you like it.

**Comment by TomasHofman** [comment]
PR: https://github.com/psss/did/pull/44
