### ISSUE TITLE
support for github, fedorahosted trac, JIRA

### ISSUE THREAD

**Issue by pnemade** [psss/did#47]
Hi,
  I just read documentation and have not found how to get status report for github projects, fedorahosted trac. For JIRA can you please add example, how to write it in config file? 
  Please add support for fedorahosted trac ticket status.

**Comment by psss** [comment]
Hi, thanks for the question. I believe all of these should be already documented. For the whole config example see:

* http://did.readthedocs.org/en/latest/config/#example

It shows github, jira and trac configuration. If you need more detailed help have a look into the plugin documentation:

 * http://did.readthedocs.org/en/latest/plugins/

For fedorahosted Trac use the `trac` plugin:

 * http://did.readthedocs.org/en/latest/plugins/#trac

Note, that you need to enable xmlrpc access for the Trac instance.
