### ISSUE TITLE
$DID_CONFIG is ignored

### ISSUE THREAD

**Issue by mcepl** [psss/did#68]
Using did from 80b4f9c and despite assurances on #43 `DID_CONFIG` variable doesn’t seem to make much difference:
```
matej@mitmanek: ~$ echo $DID_CONFIG
/home/matej/.config/did
matej@mitmanek: ~$ ls $DID_CONFIG/config
/home/matej/.config/did/config
matej@mitmanek: ~$ did --since=2015-09-22
Create at least a minimum config file /home/matej/.did/config:
[general]
email = Name Surname <email@example.org>
 ERROR  Unable to read the config file '/home/matej/.did/config'.
matej@mitmanek: ~$
```

**Comment by mcepl** [comment]
Oh, it just randomly changed to `DID_DIR`. Lovely.

**Comment by psss** [comment]
Sorry for that. The tool is still a bit young and there can be here and there some incompatible changes especially in those areas which are very fresh (like the `DID_DIR` variable). But I don't expect many of them. Once we hit `1.0.0` I will be definitely a bit more conservative ;-)
