### ISSUE TITLE
New plugin: Errata tool

### ISSUE THREAD

**Issue by xersin** [psss/did#78]
It'd be cool to be able to query changes done to Errata Tool. I have some scripts which are able to access the tool, please ping me offline if interested. Unfortunately I don't have the time to work on this now;-/

**Comment by psss** [comment]
Thanks for the idea, Stanislav. As the Errata Tool is not available to public it probably does not make sense to create plugins for it here on GitHub. However, we have an internal plugin which, for now, only lists completed errata. We can extend it according to user needs.

**Comment by xersin** [comment]
Sounds good, thanks for reply!
