### ISSUE TITLE
Github plugin: differentiate issues and pull requests

### ISSUE THREAD

**Issue by dkutalek** [psss/did#93]
According to:
https://developer.github.com/v3/issues/

Note: In the past, pull requests and issues were more closely aligned than they are now. As far as the API is concerned, every pull request is an issue, but not every issue is a pull request.

This endpoint may also return pull requests in the response. If an issue is a pull request, the object will include a pull_request key.

**Comment by psss** [comment]
Martin's pull request has been merged to master. Closing.
